trigger:
  branches:
    include:
      - main

variables:
  imageName: 'fcg-api'
  dockerRegistry: 'fiapcloudgamesacr.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build Docker Image and Push to ACR
  jobs:
  - job: Build
    pool: self-hosted
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
    - script: |
        echo "Building Docker image"
        docker build -t $(dockerRegistry)/$(imageName):$(tag) .
      displayName: Build Docker Image
    - script: |
        echo "Login and push to ACR"
        docker login $(dockerRegistry) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
        docker push $(dockerRegistry)/$(imageName):$(tag)
      displayName: Push Docker Image
      env:
        ACR_USERNAME: $(ACR_USERNAME)
        ACR_PASSWORD: $(ACR_PASSWORD)

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: BuildAndPush
  condition: succeeded()
  jobs:
  - job: DeployJob
    pool: self-hosted
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy Container to Web App
      inputs:
        azureSubscription: 'FiapConnection'
        appName: 'FiapCloudGamesApi'
        containers: '$(dockerRegistry)/$(imageName):$(tag)'
