@FiapCloudGames_HostAddress = http://localhost:7131

GET {{FiapCloudGames_HostAddress}}/weatherforecast/
Accept: application/json

###

### Login perfil ADMINISTRADOR
POST https://localhost:7131/api/Login/login
Content-Type: application/json

{
  "email": "mickey@gmail.com",
  "senha": "Fiap@123"
}


###

### Login perfil USUARIO
POST https://localhost:7131/api/Login/login
Content-Type: application/json

{
  "email": "peter@fiap.com",
  "senha": "Fiap@123"
}

###

### Endpoint público (acesso livre)
GET https://localhost:7131/api/Login/publico
Accept: application/json

###

### Endpoint autenticado (qualquer usuário autenticado)
GET https://localhost:7131/api/Login/autenticado
Authorization: Bearer 
Accept: application/json

###

### Endpoint restrito ao perfil USUARIO
GET https://localhost:7131/api/Login/usuario
Authorization: Bearer 
Accept: application/json

###

### Endpoint restrito ao perfil ADMINISTRADOR
GET https://localhost:7131/api/Login/admin
Authorization: Bearer 
Accept: application/json
